# Generated by Django 3.0.8 on 2021-01-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myawardtask',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='Award/%Y/%m/%d/', verbose_name='懸賞任務'),
        ),
    ]
