# Generated by Django 3.1.1 on 2020-11-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_vaild',
            field=models.BooleanField(default=False),
        ),
    ]
