# Generated by Django 3.0.8 on 2021-01-01 12:05

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(verbose_name='結束時間'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(verbose_name='開始時間'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='主題'),
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='標題')),
                ('content', ckeditor.fields.RichTextField(verbose_name='說明')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='calendars/%Y/%m/%d/', verbose_name='照片')),
                ('slug', django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=8, unique=True, unique_for_date='publish')),
                ('publish', models.DateField(auto_now=True, verbose_name='發布日期')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_owner', to=settings.AUTH_USER_MODEL, verbose_name='發起人')),
            ],
            options={
                'ordering': ['-publish'],
            },
        ),
    ]
