# Generated by Django 3.1.1 on 2020-12-27 04:09

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201227_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='myworktask',
            name='slug',
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=32, unique=True, unique_for_date='publish'),
        ),
    ]
