# Generated by Django 3.0.8 on 2021-02-09 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210128_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='self_introduction',
            field=models.TextField(default='', verbose_name='自我介紹'),
        ),
    ]
