# Generated by Django 3.1.1 on 2020-11-11 01:40

import datetime
from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_task_is_vaild'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personaltask',
            options={'ordering': ['-assign_date']},
        ),
        migrations.RemoveField(
            model_name='personaltask',
            name='date1',
        ),
        migrations.AddField(
            model_name='personaltask',
            name='assign_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='指派日期'),
        ),
        migrations.AddField(
            model_name='personaltask',
            name='finish_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='完成日期'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personaltask',
            name='slug',
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=8, unique=True, unique_for_date='assign_date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_vaild',
            field=models.BooleanField(default=True),
        ),
    ]
