# Generated by Django 3.0.8 on 2021-01-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210101_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='end_time',
            field=models.DateTimeField(null=True, verbose_name='結束時間'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='start_time',
            field=models.DateTimeField(null=True, verbose_name='開始時間'),
        ),
    ]
