# Generated by Django 3.1.1 on 2020-11-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201111_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaltask',
            name='finish_date',
            field=models.DateField(blank=True, null=True, verbose_name='完成日期'),
        ),
    ]
