# Generated by Django 3.1.1 on 2020-12-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_myworktask_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myworktask',
            name='date',
            field=models.DateField(auto_created=True, null=True),
        ),
    ]
