# Generated by Django 3.0.8 on 2021-01-01 14:24

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210101_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='slug',
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=32, unique=True, unique_for_date='transaction_date'),
        ),
    ]
