# Generated by Django 3.0.8 on 2021-02-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userprofile_self_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='open_point',
            field=models.BooleanField(default=False, verbose_name='開放點數查詢'),
        ),
    ]
