# Generated by Django 3.1.2 on 2020-12-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201227_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='myworktask',
            name='isfinish',
            field=models.BooleanField(default=False),
        ),
    ]
