# Generated by Django 3.0.8 on 2021-01-01 17:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_account_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calendar',
            new_name='Calendars',
        ),
        migrations.AlterField(
            model_name='account',
            name='transaction_memo',
            field=models.CharField(choices=[('家屬購買', '家屬購買'), ('task', '任務所得'), ('other', '其他')], default=' ', max_length=40, verbose_name='交易內容'),
        ),
    ]
