# Generated by Django 3.1.1 on 2020-11-14 03:43

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201111_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltask',
            name='is_award',
            field=models.BooleanField(default=False, verbose_name='是否獎勵過'),
        ),
        migrations.AddField(
            model_name='personaltask',
            name='point',
            field=models.IntegerField(default=0, verbose_name='點數'),
        ),
        migrations.AlterField(
            model_name='personaltask',
            name='slug',
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=32, unique=True, unique_for_date='assign_date'),
        ),
    ]
