# Generated by Django 3.1.1 on 2020-12-28 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_myworktask_isfinish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myworktask',
            name='end_time',
            field=models.DateTimeField(null=True, verbose_name='任務結束時間'),
        ),
        migrations.AlterField(
            model_name='myworktask',
            name='start_time',
            field=models.DateTimeField(null=True, verbose_name='任務開始時間'),
        ),
    ]
