# Generated by Django 3.0.8 on 2021-02-11 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210211_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamtask',
            name='is_vaild',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='teamtask',
            name='point',
            field=models.IntegerField(default=0, verbose_name='需求點數'),
        ),
    ]
