# Generated by Django 3.1.1 on 2020-11-20 07:32

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_auto_20201114_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donate_date', models.DateField(default=django.utils.timezone.now, verbose_name='捐款日期')),
                ('donate_points', models.IntegerField(verbose_name='團隊所得點數')),
            ],
        ),
        migrations.CreateModel(
            name='MyTeamTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_award', models.BooleanField(default=False, verbose_name='是否獎勵過')),
                ('point', models.IntegerField(default=0, verbose_name='點數')),
            ],
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='task',
        ),
        migrations.RemoveField(
            model_name='group',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='teamtask',
            name='group',
        ),
        migrations.RemoveField(
            model_name='teamtask',
            name='task',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='group',
        ),
        migrations.AddField(
            model_name='account',
            name='deposit',
            field=models.IntegerField(default=0, verbose_name='入賬'),
        ),
        migrations.AddField(
            model_name='account',
            name='transaction_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='交易日期'),
        ),
        migrations.AddField(
            model_name='account',
            name='withdraw',
            field=models.IntegerField(default=0, verbose_name='提款'),
        ),
        migrations.AddField(
            model_name='group',
            name='slug',
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=32, unique=True, unique_for_date='publish'),
        ),
        migrations.AddField(
            model_name='group',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.teamtask', verbose_name='團隊任務'),
        ),
        migrations.AddField(
            model_name='teamtask',
            name='end_date',
            field=models.DateField(null=True, verbose_name='活動結束時間'),
        ),
        migrations.AddField(
            model_name='teamtask',
            name='point',
            field=models.IntegerField(default=0, verbose_name='點數'),
        ),
        migrations.AddField(
            model_name='teamtask',
            name='publish',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='任務發布時間'),
        ),
        migrations.AddField(
            model_name='teamtask',
            name='slug',
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=32, unique=True, unique_for_date='publish'),
        ),
        migrations.AddField(
            model_name='teamtask',
            name='start_date',
            field=models.DateField(null=True, verbose_name='活動開始時間'),
        ),
        migrations.AddField(
            model_name='teamtask',
            name='task_content',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='任務內容'),
        ),
        migrations.AddField(
            model_name='teamtask',
            name='task_name',
            field=models.CharField(max_length=32, null=True, verbose_name='任務名稱'),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='住民名字', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=32, unique=True, unique_for_date='publish'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('daily_task', '每日任務'), ('work_task', '工作任務')], default='daily_task', max_length=12, verbose_name='任務型別'),
        ),
        migrations.DeleteModel(
            name='PersonalSubTask',
        ),
        migrations.AddField(
            model_name='myteamtask',
            name='group',
            field=models.ManyToManyField(to='app.Group'),
        ),
        migrations.AddField(
            model_name='myteamtask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='名字'),
        ),
        migrations.AddField(
            model_name='donate',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.group', verbose_name='群組'),
        ),
        migrations.AddField(
            model_name='donate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='捐款人'),
        ),
    ]
