# Generated by Django 3.0.8 on 2021-02-11 15:01

import ckeditor.fields
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210211_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='subteamtask',
            name='publish',
            field=models.DateField(auto_now=True, verbose_name='任務發布時間'),
        ),
        migrations.AddField(
            model_name='subteamtask',
            name='slug',
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=32, unique=True, unique_for_date='publish'),
        ),
        migrations.AlterField(
            model_name='subteamtask',
            name='task_content',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='方案內容'),
        ),
    ]
