# Generated by Django 3.1.1 on 2020-12-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201228_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='transaction_memo',
            field=models.CharField(default=' ', max_length=40, verbose_name='交易內容'),
        ),
    ]
