# Generated by Django 3.1.1 on 2020-11-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201120_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='myteamtask',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否獎勵過'),
        ),
    ]
