# Generated by Django 3.1.1 on 2020-11-23 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_myteamtask_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myteamtask',
            name='is_active',
        ),
        migrations.AddField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=32, null=True, verbose_name='隊名'),
        ),
        migrations.AddField(
            model_name='group',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否獎勵過'),
        ),
        migrations.AddField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='auth.user', verbose_name='隊長'),
            preserve_default=False,
        ),
    ]
