# Generated by Django 3.1.1 on 2020-11-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201123_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(default='', max_length=32, null=True, verbose_name='隊名'),
        ),
    ]
