# Generated by Django 3.1.1 on 2020-12-08 01:57

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_auto_20201124_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myteamtask',
            name='group',
            field=models.ManyToManyField(related_name='group', to='app.Group'),
        ),
        migrations.CreateModel(
            name='MyAwardTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=32, null=True, verbose_name='任務名稱')),
                ('task_content', ckeditor.fields.RichTextField(null=True, verbose_name='任務內容')),
                ('slug', django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=32, unique=True, unique_for_date='publish')),
                ('publish', models.DateField(default=django.utils.timezone.now, verbose_name='任務發布時間')),
                ('point', models.IntegerField(default=0, verbose_name='支付點數')),
                ('approve_time', models.DateField(null=True, verbose_name='任務核可時間')),
                ('accept_time', models.DateField(null=True, verbose_name='任務接受時間')),
                ('accept_man', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accept_man', to=settings.AUTH_USER_MODEL, verbose_name='任務接受人')),
                ('approve_man', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approve_man', to=settings.AUTH_USER_MODEL, verbose_name='任務核可人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awardtask_user', to=settings.AUTH_USER_MODEL, verbose_name='名字')),
            ],
        ),
    ]
