# Generated by Django 3.1.1 on 2020-12-14 08:49

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20201208_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=32, null=True, verbose_name='任務名稱')),
                ('task_content', ckeditor.fields.RichTextField(null=True, verbose_name='任務內容')),
                ('slug', django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=32, unique=True, unique_for_date='publish')),
                ('task_start_time', models.DateField(null=True, verbose_name='任務開始時間')),
                ('task_end_time', models.DateField(null=True, verbose_name='任務結束時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worktask_assigner', to='app.userprofile', verbose_name='任務發布者')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worktask_accepter', to='app.userprofile', verbose_name='任務接受者')),
            ],
        ),
    ]
