# Generated by Django 3.1.1 on 2020-12-23 02:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_worktask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worktask',
            name='task_end_time',
        ),
        migrations.RemoveField(
            model_name='worktask',
            name='task_start_time',
        ),
        migrations.RemoveField(
            model_name='worktask',
            name='worker',
        ),
        migrations.AddField(
            model_name='worktask',
            name='point',
            field=models.IntegerField(default=0, verbose_name='點數'),
        ),
        migrations.AddField(
            model_name='worktask',
            name='publish',
            field=models.DateField(auto_created=True, default=django.utils.timezone.now, verbose_name='發布日期'),
        ),
        migrations.CreateModel(
            name='MyWorkTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.DateField(auto_created=True, verbose_name='發布日期')),
                ('slug', django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=32, unique=True, unique_for_date='publish')),
                ('start_time', models.DateField(verbose_name='開始時間')),
                ('end_time', models.DateField(verbose_name='結束時間')),
                ('point', models.IntegerField(default=0, verbose_name='點數')),
                ('task_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worktask', to='app.worktask', verbose_name='工作任務')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worktask_accepter', to='app.userprofile', verbose_name='任務接受者')),
            ],
        ),
    ]
