# Generated by Django 3.1.1 on 2020-12-22 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_worktask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worktask',
            name='task_end_time',
        ),
        migrations.RemoveField(
            model_name='worktask',
            name='task_start_time',
        ),
        migrations.RemoveField(
            model_name='worktask',
            name='worker',
        ),
        migrations.AddField(
            model_name='worktask',
            name='point',
            field=models.IntegerField(default=0, verbose_name='獲得點數'),
        ),
        migrations.CreateModel(
            name='MyWorkTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('start_time', models.DateField(verbose_name='任務開始時間')),
                ('end_time', models.DateField(verbose_name='任務結束時間')),
                ('point', models.IntegerField(default=0, verbose_name='獲得點數')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myworktask', to='app.worktask', verbose_name='任務名稱')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myworktask_accepter', to='app.userprofile', verbose_name='任務接受者')),
            ],
        ),
    ]
