# Generated by Django 3.1.1 on 2020-12-22 02:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20201222_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktask',
            name='publish',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='任務發布時間'),
        ),
    ]
