# Generated by Django 3.1.1 on 2020-10-16 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority', models.CharField(choices=[('管理者', 'admin'), ('照服員', 'employee'), ('住民', 'resident'), ('家屬', 'family'), ('廠商', 'vendor')], default='住民', max_length=20)),
                ('Photo', models.ImageField(null=True, upload_to='users/%Y/%m/%d/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
